### PR TITLE
fix : component style and feat : more btn, badges, textarea

### PR DESCRIPTION
**Pull request by mikesch803**
i create a new branch (review-dev) to fix some minor changes to components, add some btn, textarea, and badges,

### CODE REVIEW

**Review by abhisheksahani-nova — APPROVED** [review]
LGTM

**Review by ArjunJunna — COMMENTED** [review]
Looks fine

**Review by ArjunJunna — APPROVED** [review]
looks fine

**Review by MayankKumar10 — COMMENTED** [review]
LGTM you can merge it

**Pull request merged**
