### PR TITLE
feat : btn and alert

### PR DESCRIPTION
**Pull request by mikesch803**
alert with different style and btns with icon, flot-btn, and primary and secondary btn

### CODE REVIEW

**Comment by hsnice16** [comment]
Everything looks good, nice work 👍

**Comment by Dev-AkshatGupta** [comment]
+1 Looks good to me keep on doing the good work

**Review by nayyyhaa — APPROVED** [review]
LGTM! Can merge the changes :)

**Comment by mikesch803** [comment]
> Everything looks good, nice work 👍

**Pull request merged**
